export const GET_ALL_POKEMONS = 'GETALLPOKEMONS';
export const GET_PAGE_POKEMONS = 'GETPAGEPOKEMONS';
export const GET_POKEMON_BY_NAME = "GETPOKEMONBYNAME";
export const GET_DETAIL_POKEMONS = 'GETDETAILPOKEMONS';
